# Generated by Django 5.2.9 on 2025-12-13 17:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_remove_news_updated_at_alter_news_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='published_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
