# Generated by Django 5.2.9 on 2025-12-11 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('guest', 'Гость'), ('client', 'Клиент'), ('manager', 'Менеджер'), ('admin', 'Админ')], default='client', max_length=20),
        ),
    ]
