# Generated by Django 5.2.9 on 2025-12-13 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('client', 'Клиент'), ('manager', 'Менеджер'), ('admin', 'Админ')], default='client', max_length=20),
        ),
    ]
